# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 499f11ccaf6e9758172252e7c3b3949c25543ad7e9fcfb8c8c0bfb333287facb77148cb8da54794c2e7b753a9dff51b8752a4e78fca4a8c81c46345d408ad0ca

test:
  secret_key_base: 673df607b60f70f4949aa7e9b2d65188a5d3f950da63bf14402a5e8e212e88288587eae99aa86dff7eb39c4332f166c3dccf1cbf4b5fd9712b83ce686218d7c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
