user:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  size_gra: 80
  session: "1"

reset_pass:
  hour: 2

micropost:
  maximum_content: 140
  user: 50
  file_type: "image/jpeg,image/gif,image/png"

picture:
  size: 5
  size_limit: 400
